/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module mux2to1(a, b, sel, y);
  input a;
  wire a;
  input b;
  wire b;
  input sel;
  wire sel;
  output y;
  wire y;
  assign y = sel ? b : a;
endmodule
