/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

(* top =  1  *)
(* src = "logic_model.sv:2.1-9.10" *)
module mux2to1(a, b, sel, y);
  (* src = "logic_model.sv:3.17-3.18" *)
  input a;
  wire a;
  (* src = "logic_model.sv:4.17-4.18" *)
  input b;
  wire b;
  (* src = "logic_model.sv:5.17-5.20" *)
  input sel;
  wire sel;
  (* src = "logic_model.sv:6.17-6.18" *)
  output y;
  wire y;
  assign y = sel ? b : a;
endmodule
