/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

(* top =  1  *)
(* src = "logic_model.sv:2.1-17.10" *)
module mux2to1(a, b, sel, y);
  (* src = "logic_model.sv:3.17-3.18" *)
  input a;
  wire a;
  (* src = "logic_model.sv:4.17-4.18" *)
  input b;
  wire b;
  (* src = "logic_model.sv:5.17-5.20" *)
  input sel;
  wire sel;
  (* src = "logic_model.sv:6.17-6.18" *)
  output y;
  wire y;
  (* src = "logic_model.sv:3.17-3.18" *)
  wire _0_;
  (* src = "logic_model.sv:4.17-4.18" *)
  wire _1_;
  (* src = "logic_model.sv:5.17-5.20" *)
  wire _2_;
  (* src = "logic_model.sv:6.17-6.18" *)
  wire _3_;
  assign _3_ = _2_ ? _1_ : _0_;
  assign _0_ = a;
  assign _1_ = b;
  assign _2_ = sel;
  assign y = _3_;
endmodule
