/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module rom(address, data);
  wire _0_;
  wire _1_;
  input [2:0] address;
  wire [2:0] address;
  output [7:0] data;
  wire [7:0] data;
  assign data[5] = address[1] ^ address[0];
  assign _1_ = address[1] & address[0];
  assign _0_ = ~(address[1] & address[0]);
  assign data[6] = address[2] ? _0_ : _1_;
  assign data[7] = _1_ & address[2];
  assign data[4] = ~address[0];
  assign data[3:0] = data[7:4];
endmodule
