/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module rom(address, data);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input [2:0] address;
  output [7:0] data;
  assign _00_ = ! address;
  function [7:0] _09_;
    input [7:0] a;
    input [63:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _09_ = b[7:0];
      8'b??????1?:
        _09_ = b[15:8];
      8'b?????1??:
        _09_ = b[23:16];
      8'b????1???:
        _09_ = b[31:24];
      8'b???1????:
        _09_ = b[39:32];
      8'b??1?????:
        _09_ = b[47:40];
      8'b?1??????:
        _09_ = b[55:48];
      8'b1???????:
        _09_ = b[63:56];
      default:
        _09_ = a;
    endcase
  endfunction
  assign data = _09_(8'hxx, 64'h1122334455667788, { _00_, _07_, _06_, _05_, _04_, _03_, _02_, _01_ });
  assign _01_ = address == 3'h7;
  assign _02_ = address == 3'h6;
  assign _03_ = address == 3'h5;
  assign _04_ = address == 3'h4;
  assign _05_ = address == 3'h3;
  assign _06_ = address == 3'h2;
  assign _07_ = address == 3'h1;
endmodule
