/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module combined_gates(a, b, c, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  input [7:0] a;
  input [7:0] b;
  input [7:0] c;
  output [7:0] y;
  assign y[0] = a[0] & b[0];
  assign _00_ = a[3] & b[3];
  assign _01_ = a[7] & b[7];
  assign y[3] = ~ _00_;
  assign y[4] = ~ _02_;
  assign y[5] = ~ c[5];
  assign y[6] = ~ _03_;
  assign y[1] = a[1] | b[1];
  assign _02_ = a[4] | b[4];
  assign y[7] = _01_ | c[7];
  assign y[2] = a[2] ^ b[2];
  assign _03_ = a[6] ^ b[6];
endmodule
