/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module apb_uart(pclk, presetn, psel, penable, pwrite, paddr, pwdata, prdata, pready, pslverr, uart_rx, uart_tx, irq);
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire [4:0] _004_;
  wire [3:0] _005_;
  wire [2:0] _006_;
  wire [7:0] _007_;
  wire [7:0] _008_;
  wire [7:0] _009_;
  wire [7:0] _010_;
  wire _011_;
  wire [1:0] _012_;
  wire [7:0] _013_;
  wire [1:0] _014_;
  wire _015_;
  wire [4:0] _016_;
  wire [3:0] _017_;
  wire [2:0] _018_;
  wire [7:0] _019_;
  wire [7:0] _020_;
  wire [7:0] _021_;
  wire [7:0] _022_;
  wire [1:0] _023_;
  wire [7:0] _024_;
  wire [1:0] _025_;
  wire _026_;
  wire [7:0] _027_;
  wire [4:0] _028_;
  wire [31:0] _029_;
  wire [2:0] _030_;
  wire [31:0] _031_;
  wire [31:0] _032_;
  wire [3:0] _033_;
  wire [4:0] _034_;
  wire [3:0] _035_;
  wire [31:0] _036_;
  wire [2:0] _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire [7:0] _120_;
  wire [7:0] _121_;
  wire [7:0] _122_;
  wire [7:0] _123_;
  wire [7:0] _124_;
  wire [7:0] _125_;
  wire [7:0] _126_;
  wire _127_;
  wire [7:0] _128_;
  wire [7:0] _129_;
  wire [7:0] _130_;
  wire [7:0] _131_;
  wire [7:0] _132_;
  wire [7:0] _133_;
  wire _134_;
  wire [7:0] _135_;
  wire [7:0] _136_;
  wire [7:0] _137_;
  wire [7:0] _138_;
  wire [7:0] _139_;
  wire [7:0] _140_;
  wire _141_;
  wire [7:0] _142_;
  wire [7:0] _143_;
  wire [7:0] _144_;
  wire [7:0] _145_;
  wire [7:0] _146_;
  wire [7:0] _147_;
  wire [7:0] _148_;
  wire _149_;
  wire [7:0] _150_;
  wire _151_;
  wire [7:0] _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire [4:0] _161_;
  wire [4:0] _162_;
  wire [4:0] _163_;
  wire [4:0] _164_;
  wire [3:0] _165_;
  wire [3:0] _166_;
  wire [3:0] _167_;
  wire [3:0] _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire [2:0] _180_;
  wire [2:0] _181_;
  wire [2:0] _182_;
  wire [2:0] _183_;
  wire [2:0] _184_;
  wire [2:0] _185_;
  wire [2:0] _186_;
  wire [1:0] _187_;
  wire [1:0] _188_;
  wire [1:0] _189_;
  wire [1:0] _190_;
  wire [1:0] _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire [2:0] _196_;
  wire [2:0] _197_;
  wire [7:0] _198_;
  wire [31:0] _199_;
  wire [31:0] _200_;
  wire [31:0] _201_;
  wire [31:0] _202_;
  wire [31:0] _203_;
  wire [31:0] _204_;
  wire apb_access;
  wire apb_read;
  wire apb_write;
  reg framing_error;
  output irq;
  reg irq_enable;
  input [7:0] paddr;
  input pclk;
  input penable;
  output [31:0] prdata;
  output pready;
  input presetn;
  input psel;
  output pslverr;
  input [31:0] pwdata;
  input pwrite;
  reg rx_active;
  reg [4:0] rx_baud_count;
  reg [3:0] rx_bit_index;
  reg [2:0] rx_count;
  wire rx_empty;
  reg [7:0] \rx_fifo[0] ;
  reg [7:0] \rx_fifo[1] ;
  reg [7:0] \rx_fifo[2] ;
  reg [7:0] \rx_fifo[3] ;
  wire rx_full;
  reg rx_overrun;
  reg [1:0] rx_rd_ptr;
  reg [7:0] rx_shift;
  reg [1:0] rx_wr_ptr;
  reg tx_active;
  reg [4:0] tx_baud_count;
  reg [3:0] tx_bit_index;
  reg [2:0] tx_count;
  wire tx_empty;
  reg [7:0] \tx_fifo[0] ;
  reg [7:0] \tx_fifo[1] ;
  reg [7:0] \tx_fifo[2] ;
  reg [7:0] \tx_fifo[3] ;
  wire tx_full;
  reg [1:0] tx_rd_ptr;
  reg [7:0] tx_shift;
  reg [1:0] tx_wr_ptr;
  input uart_rx;
  output uart_tx;
  reg uart_tx;
  assign _028_ = rx_baud_count + 1'h1;
  assign _029_ = tx_wr_ptr + 1'h1;
  assign _030_ = tx_count + 1'h1;
  assign _031_ = rx_rd_ptr + 1'h1;
  assign _032_ = tx_rd_ptr + 1'h1;
  assign _033_ = tx_bit_index + 1'h1;
  assign _034_ = tx_baud_count + 1'h1;
  assign _035_ = rx_bit_index + 1'h1;
  assign _036_ = rx_wr_ptr + 1'h1;
  assign _037_ = rx_count + 1'h1;
  assign tx_full = tx_count == 3'h4;
  assign tx_empty = ! tx_count;
  assign rx_full = rx_count == 3'h4;
  assign rx_empty = ! rx_count;
  assign _039_ = paddr == 8'h08;
  assign _040_ = paddr == 8'h0c;
  assign _041_ = ! paddr;
  assign _038_ = paddr == 8'h04;
  assign _045_ = tx_baud_count == 5'h0f;
  assign _046_ = tx_bit_index == 4'h8;
  assign _047_ = rx_baud_count == 5'h0f;
  assign apb_access = psel && penable;
  assign apb_write = apb_access && pwrite;
  assign apb_read = apb_access && _059_;
  assign _049_ = _070_ && _071_;
  assign _050_ = _049_ && _072_;
  assign _051_ = _050_ && _073_;
  assign pslverr = apb_access && _051_;
  assign irq = irq_enable && _067_;
  assign _052_ = apb_write && _040_;
  assign _053_ = apb_write && _041_;
  assign _054_ = _053_ && _061_;
  assign _055_ = apb_read && _038_;
  assign _056_ = _055_ && _060_;
  assign _057_ = _062_ && _063_;
  assign _058_ = _064_ && _065_;
  assign _059_ = ! pwrite;
  assign _061_ = ! tx_full;
  assign _060_ = ! rx_empty;
  assign _062_ = ! tx_active;
  assign _063_ = ! tx_empty;
  assign _064_ = ! rx_active;
  assign _065_ = ! uart_rx;
  assign _066_ = _060_ || rx_overrun;
  assign _067_ = _066_ || framing_error;
  assign _068_ = tx_bit_index < 32'd8;
  assign _069_ = rx_bit_index < 32'd8;
  assign _070_ = | paddr;
  assign _071_ = paddr != 8'h04;
  assign _072_ = paddr != 8'h08;
  assign _073_ = paddr != 8'h0c;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      uart_tx <= 1'h1;
    else
      uart_tx <= _026_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      tx_wr_ptr <= 2'h0;
    else
      tx_wr_ptr <= _025_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      tx_rd_ptr <= 2'h0;
    else
      tx_rd_ptr <= _023_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      rx_wr_ptr <= 2'h0;
    else
      rx_wr_ptr <= _014_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      rx_rd_ptr <= 2'h0;
    else
      rx_rd_ptr <= _012_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      tx_count <= 3'h0;
    else
      tx_count <= _018_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      rx_count <= 3'h0;
    else
      rx_count <= _006_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      rx_overrun <= 1'h0;
    else
      rx_overrun <= _011_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      framing_error <= 1'h0;
    else
      framing_error <= _001_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      irq_enable <= 1'h0;
    else
      irq_enable <= _002_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      tx_bit_index <= 4'h0;
    else
      tx_bit_index <= _017_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      rx_bit_index <= 4'h0;
    else
      rx_bit_index <= _005_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      tx_shift <= 8'h00;
    else
      tx_shift <= _024_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      rx_shift <= 8'h00;
    else
      rx_shift <= _013_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      tx_baud_count <= 5'h00;
    else
      tx_baud_count <= _016_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      rx_baud_count <= 5'h00;
    else
      rx_baud_count <= _004_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      tx_active <= 1'h0;
    else
      tx_active <= _015_;
  always @(posedge pclk or negedge presetn)
    if (!presetn)
      rx_active <= 1'h0;
    else
      rx_active <= _003_;
  always @(posedge pclk)
      \tx_fifo[0]  <= _019_;
  always @(posedge pclk)
      \tx_fifo[1]  <= _020_;
  always @(posedge pclk)
      \tx_fifo[2]  <= _021_;
  always @(posedge pclk)
      \tx_fifo[3]  <= _022_;
  always @(posedge pclk)
      \rx_fifo[0]  <= _007_;
  always @(posedge pclk)
      \rx_fifo[1]  <= _008_;
  always @(posedge pclk)
      \rx_fifo[2]  <= _009_;
  always @(posedge pclk)
      \rx_fifo[3]  <= _010_;
  function [7:0] _282_;
    input [7:0] a;
    input [31:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _282_ = b[7:0];
      4'b??1?:
        _282_ = b[15:8];
      4'b?1??:
        _282_ = b[23:16];
      4'b1???:
        _282_ = b[31:24];
      default:
        _282_ = a;
    endcase
  endfunction
  assign _000_ = _282_(8'hxx, { \rx_fifo[0] , \rx_fifo[1] , \rx_fifo[2] , \rx_fifo[3]  }, { _076_, _075_, _074_, _043_ });
  assign _043_ = rx_rd_ptr == 2'h3;
  assign _074_ = rx_rd_ptr == 2'h2;
  assign _075_ = rx_rd_ptr == 2'h1;
  assign _076_ = ! rx_rd_ptr;
  assign _077_ = _078_ ? uart_rx : rx_shift[7];
  assign _078_ = rx_bit_index == 4'h7;
  assign _079_ = _069_ ? _077_ : rx_shift[7];
  assign _080_ = _047_ ? _079_ : rx_shift[7];
  assign _081_ = rx_active ? _080_ : rx_shift[7];
  assign _013_[7] = _058_ ? 1'h0 : _081_;
  assign _082_ = _083_ ? uart_rx : rx_shift[6];
  assign _083_ = rx_bit_index == 4'h6;
  assign _084_ = _069_ ? _082_ : rx_shift[6];
  assign _085_ = _047_ ? _084_ : rx_shift[6];
  assign _086_ = rx_active ? _085_ : rx_shift[6];
  assign _013_[6] = _058_ ? 1'h0 : _086_;
  assign _087_ = _088_ ? uart_rx : rx_shift[5];
  assign _088_ = rx_bit_index == 4'h5;
  assign _089_ = _069_ ? _087_ : rx_shift[5];
  assign _090_ = _047_ ? _089_ : rx_shift[5];
  assign _091_ = rx_active ? _090_ : rx_shift[5];
  assign _013_[5] = _058_ ? 1'h0 : _091_;
  assign _092_ = _093_ ? uart_rx : rx_shift[4];
  assign _093_ = rx_bit_index == 4'h4;
  assign _094_ = _069_ ? _092_ : rx_shift[4];
  assign _095_ = _047_ ? _094_ : rx_shift[4];
  assign _096_ = rx_active ? _095_ : rx_shift[4];
  assign _013_[4] = _058_ ? 1'h0 : _096_;
  assign _097_ = _098_ ? uart_rx : rx_shift[3];
  assign _098_ = rx_bit_index == 4'h3;
  assign _099_ = _069_ ? _097_ : rx_shift[3];
  assign _100_ = _047_ ? _099_ : rx_shift[3];
  assign _101_ = rx_active ? _100_ : rx_shift[3];
  assign _013_[3] = _058_ ? 1'h0 : _101_;
  assign _102_ = _103_ ? uart_rx : rx_shift[2];
  assign _103_ = rx_bit_index == 4'h2;
  assign _104_ = _069_ ? _102_ : rx_shift[2];
  assign _105_ = _047_ ? _104_ : rx_shift[2];
  assign _106_ = rx_active ? _105_ : rx_shift[2];
  assign _013_[2] = _058_ ? 1'h0 : _106_;
  assign _107_ = _108_ ? uart_rx : rx_shift[1];
  assign _108_ = rx_bit_index == 4'h1;
  assign _109_ = _069_ ? _107_ : rx_shift[1];
  assign _110_ = _047_ ? _109_ : rx_shift[1];
  assign _111_ = rx_active ? _110_ : rx_shift[1];
  assign _013_[1] = _058_ ? 1'h0 : _111_;
  assign _112_ = _113_ ? uart_rx : rx_shift[0];
  assign _113_ = ! rx_bit_index;
  assign _114_ = _069_ ? _112_ : rx_shift[0];
  assign _115_ = _047_ ? _114_ : rx_shift[0];
  assign _116_ = rx_active ? _115_ : rx_shift[0];
  assign _013_[0] = _058_ ? 1'h0 : _116_;
  function [7:0] _335_;
    input [7:0] a;
    input [31:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _335_ = b[7:0];
      4'b??1?:
        _335_ = b[15:8];
      4'b?1??:
        _335_ = b[23:16];
      4'b1???:
        _335_ = b[31:24];
      default:
        _335_ = a;
    endcase
  endfunction
  assign _027_ = _335_(8'hxx, { \tx_fifo[0] , \tx_fifo[1] , \tx_fifo[2] , \tx_fifo[3]  }, { _119_, _118_, _117_, _044_ });
  assign _044_ = tx_rd_ptr == 2'h3;
  assign _117_ = tx_rd_ptr == 2'h2;
  assign _118_ = tx_rd_ptr == 2'h1;
  assign _119_ = ! tx_rd_ptr;
  assign _120_ = _048_ ? rx_shift : \rx_fifo[3] ;
  assign _048_ = rx_wr_ptr == 2'h3;
  assign _121_ = rx_full ? \rx_fifo[3]  : _120_;
  assign _122_ = uart_rx ? _121_ : \rx_fifo[3] ;
  assign _123_ = _069_ ? \rx_fifo[3]  : _122_;
  assign _124_ = _047_ ? _123_ : \rx_fifo[3] ;
  assign _125_ = rx_active ? _124_ : \rx_fifo[3] ;
  assign _010_ = _058_ ? \rx_fifo[3]  : _125_;
  assign _126_ = _127_ ? rx_shift : \rx_fifo[2] ;
  assign _127_ = rx_wr_ptr == 2'h2;
  assign _128_ = rx_full ? \rx_fifo[2]  : _126_;
  assign _129_ = uart_rx ? _128_ : \rx_fifo[2] ;
  assign _130_ = _069_ ? \rx_fifo[2]  : _129_;
  assign _131_ = _047_ ? _130_ : \rx_fifo[2] ;
  assign _132_ = rx_active ? _131_ : \rx_fifo[2] ;
  assign _009_ = _058_ ? \rx_fifo[2]  : _132_;
  assign _133_ = _134_ ? rx_shift : \rx_fifo[1] ;
  assign _134_ = rx_wr_ptr == 2'h1;
  assign _135_ = rx_full ? \rx_fifo[1]  : _133_;
  assign _136_ = uart_rx ? _135_ : \rx_fifo[1] ;
  assign _137_ = _069_ ? \rx_fifo[1]  : _136_;
  assign _138_ = _047_ ? _137_ : \rx_fifo[1] ;
  assign _139_ = rx_active ? _138_ : \rx_fifo[1] ;
  assign _008_ = _058_ ? \rx_fifo[1]  : _139_;
  assign _140_ = _141_ ? rx_shift : \rx_fifo[0] ;
  assign _141_ = ! rx_wr_ptr;
  assign _142_ = rx_full ? \rx_fifo[0]  : _140_;
  assign _143_ = uart_rx ? _142_ : \rx_fifo[0] ;
  assign _144_ = _069_ ? \rx_fifo[0]  : _143_;
  assign _145_ = _047_ ? _144_ : \rx_fifo[0] ;
  assign _146_ = rx_active ? _145_ : \rx_fifo[0] ;
  assign _007_ = _058_ ? \rx_fifo[0]  : _146_;
  assign _147_ = _042_ ? pwdata[7:0] : \tx_fifo[3] ;
  assign _042_ = tx_wr_ptr == 2'h3;
  assign _022_ = _054_ ? _147_ : \tx_fifo[3] ;
  assign _148_ = _149_ ? pwdata[7:0] : \tx_fifo[2] ;
  assign _149_ = tx_wr_ptr == 2'h2;
  assign _021_ = _054_ ? _148_ : \tx_fifo[2] ;
  assign _150_ = _151_ ? pwdata[7:0] : \tx_fifo[1] ;
  assign _151_ = tx_wr_ptr == 2'h1;
  assign _020_ = _054_ ? _150_ : \tx_fifo[1] ;
  assign _152_ = _153_ ? pwdata[7:0] : \tx_fifo[0] ;
  assign _153_ = ! tx_wr_ptr;
  assign _019_ = _054_ ? _152_ : \tx_fifo[0] ;
  assign _154_ = _069_ ? 1'h1 : 1'h0;
  assign _155_ = _047_ ? _154_ : 1'h1;
  assign _156_ = rx_active ? _155_ : 1'h0;
  assign _003_ = _058_ ? 1'h1 : _156_;
  assign _157_ = _046_ ? 1'h1 : 1'h0;
  assign _158_ = _068_ ? 1'h1 : _157_;
  assign _159_ = _045_ ? _158_ : 1'h1;
  assign _160_ = tx_active ? _159_ : 1'h0;
  assign _015_ = _057_ ? 1'h1 : _160_;
  assign _161_ = _047_ ? 5'h00 : _028_;
  assign _162_ = rx_active ? _161_ : rx_baud_count;
  assign _004_ = _058_ ? 5'h00 : _162_;
  assign _163_ = _045_ ? 5'h00 : _034_;
  assign _164_ = tx_active ? _163_ : tx_baud_count;
  assign _016_ = _057_ ? 5'h00 : _164_;
  assign _024_ = _057_ ? _027_ : tx_shift;
  assign _165_ = _047_ ? _035_ : rx_bit_index;
  assign _166_ = rx_active ? _165_ : rx_bit_index;
  assign _005_ = _058_ ? 4'h0 : _166_;
  assign _167_ = _045_ ? _033_ : tx_bit_index;
  assign _168_ = tx_active ? _167_ : tx_bit_index;
  assign _017_ = _057_ ? 4'h0 : _168_;
  assign _002_ = _052_ ? pwdata[0] : irq_enable;
  assign _169_ = _056_ ? 1'h0 : framing_error;
  assign _170_ = uart_rx ? _169_ : 1'h1;
  assign _171_ = _069_ ? _169_ : _170_;
  assign _172_ = _047_ ? _171_ : _169_;
  assign _173_ = rx_active ? _172_ : _169_;
  assign _001_ = _058_ ? _169_ : _173_;
  assign _174_ = _056_ ? 1'h0 : rx_overrun;
  assign _175_ = rx_full ? 1'h1 : _174_;
  assign _176_ = uart_rx ? _175_ : _174_;
  assign _177_ = _069_ ? _174_ : _176_;
  assign _178_ = _047_ ? _177_ : _174_;
  assign _179_ = rx_active ? _178_ : _174_;
  assign _011_ = _058_ ? _174_ : _179_;
  assign _180_ = _056_ ? _196_ : rx_count;
  assign _181_ = rx_full ? _180_ : _037_;
  assign _182_ = uart_rx ? _181_ : _180_;
  assign _183_ = _069_ ? _180_ : _182_;
  assign _184_ = _047_ ? _183_ : _180_;
  assign _185_ = rx_active ? _184_ : _180_;
  assign _006_ = _058_ ? _180_ : _185_;
  assign _186_ = _054_ ? _030_ : tx_count;
  assign _018_ = _057_ ? _197_ : _186_;
  assign _012_ = _056_ ? _202_[1:0] : rx_rd_ptr;
  assign _187_ = rx_full ? rx_wr_ptr : _204_[1:0];
  assign _188_ = uart_rx ? _187_ : rx_wr_ptr;
  assign _189_ = _069_ ? rx_wr_ptr : _188_;
  assign _190_ = _047_ ? _189_ : rx_wr_ptr;
  assign _191_ = rx_active ? _190_ : rx_wr_ptr;
  assign _014_ = _058_ ? rx_wr_ptr : _191_;
  assign _023_ = _057_ ? _203_[1:0] : tx_rd_ptr;
  assign _025_ = _054_ ? _201_[1:0] : tx_wr_ptr;
  assign _192_ = _068_ ? _195_ : 1'h1;
  assign _193_ = _045_ ? _192_ : uart_tx;
  assign _194_ = tx_active ? _193_ : uart_tx;
  assign _026_ = _057_ ? 1'h0 : _194_;
  wire [7:0] _453_ = tx_shift;
  assign _195_ = _453_[tx_bit_index +: 1];
  assign _196_ = rx_count - 1'h1;
  assign _197_ = tx_count - 1'h1;
  assign _198_ = rx_empty ? 8'h00 : _000_;
  assign _199_ = _040_ ? { 31'h00000000, irq_enable } : 32'd0;
  assign _200_ = _039_ ? { 26'h0000000, framing_error, rx_overrun, rx_full, rx_empty, tx_full, tx_empty } : _199_;
  assign prdata = _038_ ? { 24'h000000, _198_ } : _200_;
  assign _201_ = _042_ ? 32'd0 : _029_;
  assign _202_ = _043_ ? 32'd0 : _031_;
  assign _203_ = _044_ ? 32'd0 : _032_;
  assign _204_ = _048_ ? 32'd0 : _036_;
  assign pready = 1'h1;
endmodule
