/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module logic_gates(a, b, and_y, or_y, not_y, nand_y, nor_y);
  input a;
  wire a;
  output and_y;
  wire and_y;
  input b;
  wire b;
  output nand_y;
  wire nand_y;
  output nor_y;
  wire nor_y;
  output not_y;
  wire not_y;
  output or_y;
  wire or_y;
  assign not_y = ~a;
  assign and_y = b & a;
  assign nand_y = ~(b & a);
  assign or_y = b | a;
  assign nor_y = ~(b | a);
endmodule
