/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module logic_gates(a, b, and_out, or_out, nand_out, nor_out);
  input a;
  output and_out;
  input b;
  output nand_out;
  output nor_out;
  output or_out;
  assign and_out = a & b;
  assign or_out = a | b;
  assign nand_out = ~(a & b);
  assign nor_out = ~(a | b);
endmodule
