/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "parametervector_and.sv:1" *)
module vector_and(a, b, y);
  (* src = "parametervector_and.sv:4" *)
  input [7:0] a;
  (* src = "parametervector_and.sv:5" *)
  input [7:0] b;
  (* src = "parametervector_and.sv:6" *)
  output [7:0] y;
  assign y[0] = a[0] & (* src = "parametervector_and.sv:13" *) b[0];
  assign y[1] = a[1] & (* src = "parametervector_and.sv:13" *) b[1];
  assign y[2] = a[2] & (* src = "parametervector_and.sv:13" *) b[2];
  assign y[3] = a[3] & (* src = "parametervector_and.sv:13" *) b[3];
  assign y[4] = a[4] & (* src = "parametervector_and.sv:13" *) b[4];
  assign y[5] = a[5] & (* src = "parametervector_and.sv:13" *) b[5];
  assign y[6] = a[6] & (* src = "parametervector_and.sv:13" *) b[6];
  assign y[7] = a[7] & (* src = "parametervector_and.sv:13" *) b[7];
endmodule
