/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module all_gates(a, b, y_and, y_nand, y_nor, y_not, y_or, y_xor);
  input a;
  input b;
  output y_and;
  output y_nand;
  output y_nor;
  output y_not;
  output y_or;
  output y_xor;
  and_gate u_and (
    .a(a),
    .b(b),
    .y(y_and)
  );
  nand_gate u_nand (
    .a(a),
    .b(b),
    .y(y_nand)
  );
  nor_gate u_nor (
    .a(a),
    .b(b),
    .y(y_nor)
  );
  not_gate u_not (
    .a(a),
    .y(y_not)
  );
  or_gate u_or (
    .a(a),
    .b(b),
    .y(y_or)
  );
  xor_gate u_xor (
    .a(a),
    .b(b),
    .y(y_xor)
  );
endmodule

module and_gate(a, b, y);
  input a;
  input b;
  output y;
  assign y = b & a;
endmodule

module nand_gate(a, b, y);
  input a;
  input b;
  output y;
  assign y = ~(b & a);
endmodule

module nor_gate(a, b, y);
  input a;
  input b;
  output y;
  assign y = ~(b | a);
endmodule

module not_gate(a, y);
  input a;
  output y;
  assign y = ~a;
endmodule

module or_gate(a, b, y);
  input a;
  input b;
  output y;
  assign y = b | a;
endmodule

module xor_gate(a, b, y);
  input a;
  input b;
  output y;
  assign y = b ^ a;
endmodule
