/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

(* top =  1  *)
(* src = "logic_model.sv:1.1-7.10" *)
module logic_model(a, b, c, y);
  (* src = "logic_model.sv:1.26-1.27" *)
  input a;
  wire a;
  (* src = "logic_model.sv:1.35-1.36" *)
  input b;
  wire b;
  (* src = "logic_model.sv:1.44-1.45" *)
  input c;
  wire c;
  (* src = "logic_model.sv:1.54-1.55" *)
  output y;
  wire y;
  wire _0_;
  assign _0_ = a & b;
  assign y = c | _0_;
endmodule
