SIM = icarus

TOPLEVEL_LANG = verilog

VERILOG_SOURCES = $(PWD)/basic_gates.sv

COCOTB_TOPLEVEL = and_gate

COCOTB_TEST_MODULES = test_half_adder

COMPILE_ARGS += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
