/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module decoder_2to4(a, y);
  input [1:0] a;
  wire [1:0] a;
  output [3:0] y;
  wire [3:0] y;
  assign y[0] = ~(a[0] | a[1]);
  assign y[1] = a[0] & ~(a[1]);
  assign y[2] = a[1] & ~(a[0]);
  assign y[3] = a[0] & a[1];
endmodule
