/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "vector_and.sv:1" *)
module vector_and(a, b, y);
  (* src = "vector_and.sv:2" *)
  input [7:0] a;
  (* src = "vector_and.sv:3" *)
  input [7:0] b;
  (* src = "vector_and.sv:4" *)
  output [7:0] y;
  assign y[0] = a[0] &(* src = "vector_and.sv:11" *)  b[0];
  assign y[1] = a[1] &(* src = "vector_and.sv:11" *)  b[1];
  assign y[2] = a[2] &(* src = "vector_and.sv:11" *)  b[2];
  assign y[3] = a[3] &(* src = "vector_and.sv:11" *)  b[3];
  assign y[4] = a[4] &(* src = "vector_and.sv:11" *)  b[4];
  assign y[5] = a[5] &(* src = "vector_and.sv:11" *)  b[5];
  assign y[6] = a[6] &(* src = "vector_and.sv:11" *)  b[6];
  assign y[7] = a[7] &(* src = "vector_and.sv:11" *)  b[7];
endmodule
