/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module mux4(d, sel, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  input [3:0] d;
  wire [3:0] d;
  input [1:0] sel;
  wire [1:0] sel;
  output y;
  wire y;
  assign _07_ = ~(sel[0] | sel[1]);
  assign _08_ = ~(sel[0] & sel[1]);
  assign _00_ = d[3] & ~(_08_);
  assign _01_ = sel[0] | ~(sel[1]);
  assign _02_ = d[2] & ~(_01_);
  assign _03_ = _02_ | _00_;
  assign _04_ = sel[1] | ~(sel[0]);
  assign _05_ = d[1] & ~(_04_);
  assign _06_ = _05_ | _03_;
  assign y = _07_ ? d[0] : _06_;
endmodule
