/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "combo_logic.sv:1" *)
module combo_logic(a, b, c, y);
  wire _0_;
  (* src = "combo_logic.sv:2" *)
  input a;
  (* src = "combo_logic.sv:3" *)
  input b;
  (* src = "combo_logic.sv:4" *)
  input c;
  (* src = "combo_logic.sv:5" *)
  output y;
  assign _0_ = b & a;
  assign y = _0_ | c;
endmodule
