/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dff_1bit(clk, d, q);
  reg \$auto$verilog_backend.cc:2184:dump_module$3  = 0;
  reg _0_;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  reg q;
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$3 ) begin end
  end
  always @* begin
  end
  initial begin
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$3 ) begin end
    _0_ = d;
  end
  always @(posedge clk) begin
      q <= _0_;
  end
endmodule
