/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module half_adder(a, b, sum, carry);
  input a;
  wire a;
  input b;
  wire b;
  output carry;
  wire carry;
  output sum;
  wire sum;
  assign sum = b ^ a;
  assign carry = b & a;
endmodule
