/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module half_adder(a, b, sum, carry);
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  output [3:0] carry;
  wire [3:0] carry;
  output [3:0] sum;
  wire [3:0] sum;
  assign sum[0] = a[0] ^ b[0];
  assign sum[1] = a[1] ^ b[1];
  assign sum[2] = a[2] ^ b[2];
  assign sum[3] = a[3] ^ b[3];
  assign carry[0] = a[0] & b[0];
  assign carry[1] = a[1] & b[1];
  assign carry[2] = a[2] & b[2];
  assign carry[3] = a[3] & b[3];
endmodule
