/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter(clk, reset, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire [7:0] _06_;
  wire [7:0] _07_;
  input clk;
  wire clk;
  output [7:0] count;
  reg [7:0] count;
  input reset;
  wire reset;
  assign _06_[0] = ~count[0];
  assign _00_ = count[0] & count[1];
  assign _01_ = count[2] & _00_;
  assign _02_ = count[3] & _01_;
  assign _07_[3] = count[3] ^ _01_;
  assign _03_ = count[4] & _02_;
  assign _07_[4] = count[4] ^ _02_;
  assign _04_ = count[5] & _03_;
  assign _07_[5] = count[5] ^ _03_;
  assign _05_ = ~(count[6] & _04_);
  assign _07_[6] = count[6] ^ _04_;
  assign _07_[7] = ~(count[7] ^ _05_);
  assign _07_[1] = count[0] ^ count[1];
  assign _07_[2] = count[2] ^ _00_;
  always @(posedge clk, posedge reset)
    if (reset) count[0] <= 1'h0;
    else count[0] <= _06_[0];
  always @(posedge clk, posedge reset)
    if (reset) count[1] <= 1'h0;
    else count[1] <= _07_[1];
  always @(posedge clk, posedge reset)
    if (reset) count[2] <= 1'h0;
    else count[2] <= _07_[2];
  always @(posedge clk, posedge reset)
    if (reset) count[3] <= 1'h0;
    else count[3] <= _07_[3];
  always @(posedge clk, posedge reset)
    if (reset) count[4] <= 1'h0;
    else count[4] <= _07_[4];
  always @(posedge clk, posedge reset)
    if (reset) count[5] <= 1'h0;
    else count[5] <= _07_[5];
  always @(posedge clk, posedge reset)
    if (reset) count[6] <= 1'h0;
    else count[6] <= _07_[6];
  always @(posedge clk, posedge reset)
    if (reset) count[7] <= 1'h0;
    else count[7] <= _07_[7];
  assign _06_[7:1] = count[7:1];
  assign _07_[0] = _06_[0];
endmodule
