/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module controller(clk, reset, start, finish, busy, done);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire [3:0] _04_;
  wire _05_;
  wire _06_;
  output busy;
  input clk;
  reg [3:0] current_state;
  output done;
  input finish;
  input reset;
  input start;
  assign busy = current_state[2] | current_state[1];
  assign _04_[1] = current_state[2] | _01_;
  assign _04_[0] = current_state[3] | _00_;
  assign _05_ = ~start;
  assign _06_ = ~finish;
  always @(posedge clk or posedge reset)
    if (reset)
      current_state[0] <= 1;
    else
      current_state[0] <= _04_[0];
  always @(posedge clk or posedge reset)
    if (reset)
      current_state[1] <= 0;
    else
      current_state[1] <= _04_[1];
  always @(posedge clk or posedge reset)
    if (reset)
      current_state[2] <= 0;
    else
      current_state[2] <= _02_;
  always @(posedge clk or posedge reset)
    if (reset)
      current_state[3] <= 0;
    else
      current_state[3] <= _03_;
  assign _03_ = finish & current_state[1];
  assign _00_ = _05_ & current_state[0];
  assign _02_ = start & current_state[0];
  assign _01_ = _06_ & current_state[1];
  assign _04_[3:2] = { _03_, _02_ };
  assign done = current_state[3];
endmodule
