/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module dff_1bit(clk, reset, d, q);
  input clk;
  input d;
  output q;
  reg q;
  input reset;
  always @(posedge clk or posedge reset)
    if (reset)
      q <= 0;
    else
      q <= d;
endmodule
