/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module logic_unit(a, b, sel, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input a;
  wire a;
  input b;
  wire b;
  input [1:0] sel;
  wire [1:0] sel;
  output y;
  wire y;
  assign _07_ = b & a;
  assign _08_ = ~(sel[0] | sel[1]);
  assign _09_ = ~(sel[0] & sel[1]);
  assign _10_ = ~(b | a);
  assign _00_ = _10_ & ~(_09_);
  assign _01_ = sel[1] & ~(sel[0]);
  assign _02_ = _01_ & ~(_07_);
  assign _03_ = _02_ | _00_;
  assign _04_ = sel[0] & ~(sel[1]);
  assign _05_ = _04_ & ~(_10_);
  assign _06_ = _05_ | _03_;
  assign y = _08_ ? _07_ : _06_;
endmodule
