/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "parameter_combinedgate.sv:1" *)
module vector_gates_combined(a, b, sel, y_and, y_or, y_xor, y_nand, y_nor, y_xnor, y_not_a, y_not_b, y_sel);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "parameter_combinedgate.sv:4" *)
  input [7:0] a;
  (* src = "parameter_combinedgate.sv:5" *)
  input [7:0] b;
  (* src = "parameter_combinedgate.sv:6" *)
  input [2:0] sel;
  (* src = "parameter_combinedgate.sv:9" *)
  output [7:0] y_and;
  (* src = "parameter_combinedgate.sv:12" *)
  output [7:0] y_nand;
  (* src = "parameter_combinedgate.sv:13" *)
  output [7:0] y_nor;
  (* src = "parameter_combinedgate.sv:15" *)
  output [7:0] y_not_a;
  (* src = "parameter_combinedgate.sv:16" *)
  output [7:0] y_not_b;
  (* src = "parameter_combinedgate.sv:10" *)
  output [7:0] y_or;
  (* src = "parameter_combinedgate.sv:19" *)
  output [7:0] y_sel;
  (* src = "parameter_combinedgate.sv:14" *)
  output [7:0] y_xnor;
  (* src = "parameter_combinedgate.sv:11" *)
  output [7:0] y_xor;
  assign y_and[1] = a[1] & (* src = "parameter_combinedgate.sv:38" *) b[1];
  assign y_and[2] = a[2] & (* src = "parameter_combinedgate.sv:38" *) b[2];
  assign y_and[3] = a[3] & (* src = "parameter_combinedgate.sv:38" *) b[3];
  assign y_and[4] = a[4] & (* src = "parameter_combinedgate.sv:38" *) b[4];
  assign y_and[0] = a[0] & (* src = "parameter_combinedgate.sv:38" *) b[0];
  assign y_and[5] = a[5] & (* src = "parameter_combinedgate.sv:38" *) b[5];
  assign y_and[6] = a[6] & (* src = "parameter_combinedgate.sv:38" *) b[6];
  assign y_and[7] = a[7] & (* src = "parameter_combinedgate.sv:38" *) b[7];
  assign y_nand[1] = ~ (* src = "parameter_combinedgate.sv:38" *) y_and[1];
  assign y_nand[2] = ~ (* src = "parameter_combinedgate.sv:38" *) y_and[2];
  assign y_nand[3] = ~ (* src = "parameter_combinedgate.sv:38" *) y_and[3];
  assign y_nand[4] = ~ (* src = "parameter_combinedgate.sv:38" *) y_and[4];
  assign y_nand[0] = ~ (* src = "parameter_combinedgate.sv:38" *) y_and[0];
  assign y_nand[5] = ~ (* src = "parameter_combinedgate.sv:38" *) y_and[5];
  assign y_nand[6] = ~ (* src = "parameter_combinedgate.sv:38" *) y_and[6];
  assign y_nand[7] = ~ (* src = "parameter_combinedgate.sv:38" *) y_and[7];
  assign y_nor[1] = ~ (* src = "parameter_combinedgate.sv:39" *) y_or[1];
  assign y_nor[2] = ~ (* src = "parameter_combinedgate.sv:39" *) y_or[2];
  assign y_nor[3] = ~ (* src = "parameter_combinedgate.sv:39" *) y_or[3];
  assign y_nor[4] = ~ (* src = "parameter_combinedgate.sv:39" *) y_or[4];
  assign y_nor[5] = ~ (* src = "parameter_combinedgate.sv:39" *) y_or[5];
  assign y_nor[6] = ~ (* src = "parameter_combinedgate.sv:39" *) y_or[6];
  assign y_nor[0] = ~ (* src = "parameter_combinedgate.sv:39" *) y_or[0];
  assign y_nor[7] = ~ (* src = "parameter_combinedgate.sv:39" *) y_or[7];
  assign y_xnor[0] = ~ (* src = "parameter_combinedgate.sv:40" *) y_xor[0];
  assign y_xnor[1] = ~ (* src = "parameter_combinedgate.sv:40" *) y_xor[1];
  assign y_xnor[2] = ~ (* src = "parameter_combinedgate.sv:40" *) y_xor[2];
  assign y_xnor[3] = ~ (* src = "parameter_combinedgate.sv:40" *) y_xor[3];
  assign y_xnor[4] = ~ (* src = "parameter_combinedgate.sv:40" *) y_xor[4];
  assign y_xnor[5] = ~ (* src = "parameter_combinedgate.sv:40" *) y_xor[5];
  assign y_xnor[6] = ~ (* src = "parameter_combinedgate.sv:40" *) y_xor[6];
  assign y_xnor[7] = ~ (* src = "parameter_combinedgate.sv:40" *) y_xor[7];
  assign y_not_a[0] = ~ (* src = "parameter_combinedgate.sv:41" *) a[0];
  assign y_not_a[1] = ~ (* src = "parameter_combinedgate.sv:41" *) a[1];
  assign y_not_a[2] = ~ (* src = "parameter_combinedgate.sv:41" *) a[2];
  assign y_not_a[3] = ~ (* src = "parameter_combinedgate.sv:41" *) a[3];
  assign y_not_a[4] = ~ (* src = "parameter_combinedgate.sv:41" *) a[4];
  assign y_not_a[5] = ~ (* src = "parameter_combinedgate.sv:41" *) a[5];
  assign y_not_a[6] = ~ (* src = "parameter_combinedgate.sv:41" *) a[6];
  assign y_not_a[7] = ~ (* src = "parameter_combinedgate.sv:41" *) a[7];
  assign y_not_b[0] = ~ (* src = "parameter_combinedgate.sv:42" *) b[0];
  assign y_not_b[1] = ~ (* src = "parameter_combinedgate.sv:42" *) b[1];
  assign y_not_b[2] = ~ (* src = "parameter_combinedgate.sv:42" *) b[2];
  assign y_not_b[3] = ~ (* src = "parameter_combinedgate.sv:42" *) b[3];
  assign y_not_b[4] = ~ (* src = "parameter_combinedgate.sv:42" *) b[4];
  assign y_not_b[5] = ~ (* src = "parameter_combinedgate.sv:42" *) b[5];
  assign y_not_b[6] = ~ (* src = "parameter_combinedgate.sv:42" *) b[6];
  assign y_not_b[7] = ~ (* src = "parameter_combinedgate.sv:42" *) b[7];
  assign y_or[1] = a[1] | (* src = "parameter_combinedgate.sv:39" *) b[1];
  assign y_or[2] = a[2] | (* src = "parameter_combinedgate.sv:39" *) b[2];
  assign y_or[3] = a[3] | (* src = "parameter_combinedgate.sv:39" *) b[3];
  assign y_or[4] = a[4] | (* src = "parameter_combinedgate.sv:39" *) b[4];
  assign y_or[5] = a[5] | (* src = "parameter_combinedgate.sv:39" *) b[5];
  assign y_or[0] = a[0] | (* src = "parameter_combinedgate.sv:39" *) b[0];
  assign y_or[6] = a[6] | (* src = "parameter_combinedgate.sv:39" *) b[6];
  assign y_or[7] = a[7] | (* src = "parameter_combinedgate.sv:39" *) b[7];
  function [7:0] _64_;
    input [7:0] a;
    input [63:0] b;
    input [7:0] s;
    (* full_case = 32'd1 *)
    (* src = "parameter_combinedgate.sv:57|parameter_combinedgate.sv:49" *)
    (* parallel_case *)
    casez (s)
      8'b???????1:
        _64_ = b[7:0];
      8'b??????1?:
        _64_ = b[15:8];
      8'b?????1??:
        _64_ = b[23:16];
      8'b????1???:
        _64_ = b[31:24];
      8'b???1????:
        _64_ = b[39:32];
      8'b??1?????:
        _64_ = b[47:40];
      8'b?1??????:
        _64_ = b[55:48];
      8'b1???????:
        _64_ = b[63:56];
      default:
        _64_ = a;
    endcase
  endfunction
  assign y_sel = _64_(8'hxx, { y_and, y_or, y_xor, y_nand, y_nor, y_xnor, y_not_a, y_not_b }, { _07_, _06_, _05_, _04_, _03_, _02_, _01_, _00_ });
  assign _00_ = sel == (* full_case = 32'd1 *) (* src = "parameter_combinedgate.sv:57|parameter_combinedgate.sv:49" *) 3'h7;
  assign _01_ = sel == (* full_case = 32'd1 *) (* src = "parameter_combinedgate.sv:56|parameter_combinedgate.sv:49" *) 3'h6;
  assign _02_ = sel == (* full_case = 32'd1 *) (* src = "parameter_combinedgate.sv:55|parameter_combinedgate.sv:49" *) 3'h5;
  assign _03_ = sel == (* full_case = 32'd1 *) (* src = "parameter_combinedgate.sv:54|parameter_combinedgate.sv:49" *) 3'h4;
  assign _04_ = sel == (* full_case = 32'd1 *) (* src = "parameter_combinedgate.sv:53|parameter_combinedgate.sv:49" *) 3'h3;
  assign _05_ = sel == (* full_case = 32'd1 *) (* src = "parameter_combinedgate.sv:52|parameter_combinedgate.sv:49" *) 3'h2;
  assign _06_ = sel == (* full_case = 32'd1 *) (* src = "parameter_combinedgate.sv:51|parameter_combinedgate.sv:49" *) 3'h1;
  assign _07_ = ! (* full_case = 32'd1 *) (* src = "parameter_combinedgate.sv:50|parameter_combinedgate.sv:49" *) sel;
  assign y_xor[1] = a[1] ^ (* src = "parameter_combinedgate.sv:40" *) b[1];
  assign y_xor[2] = a[2] ^ (* src = "parameter_combinedgate.sv:40" *) b[2];
  assign y_xor[3] = a[3] ^ (* src = "parameter_combinedgate.sv:40" *) b[3];
  assign y_xor[4] = a[4] ^ (* src = "parameter_combinedgate.sv:40" *) b[4];
  assign y_xor[5] = a[5] ^ (* src = "parameter_combinedgate.sv:40" *) b[5];
  assign y_xor[6] = a[6] ^ (* src = "parameter_combinedgate.sv:40" *) b[6];
  assign y_xor[7] = a[7] ^ (* src = "parameter_combinedgate.sv:40" *) b[7];
  assign y_xor[0] = a[0] ^ (* src = "parameter_combinedgate.sv:40" *) b[0];
endmodule
