/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "parameter_combinedgate.sv:1" *)
module vector_gates(a, b, y_and, y_or, y_xor, y_nand, y_nor, y_xnor, y_not_a, y_not_b);
  (* src = "parameter_combinedgate.sv:4" *)
  input [7:0] a;
  (* src = "parameter_combinedgate.sv:5" *)
  input [7:0] b;
  (* src = "parameter_combinedgate.sv:6" *)
  output [7:0] y_and;
  (* src = "parameter_combinedgate.sv:9" *)
  output [7:0] y_nand;
  (* src = "parameter_combinedgate.sv:10" *)
  output [7:0] y_nor;
  (* src = "parameter_combinedgate.sv:12" *)
  output [7:0] y_not_a;
  (* src = "parameter_combinedgate.sv:13" *)
  output [7:0] y_not_b;
  (* src = "parameter_combinedgate.sv:7" *)
  output [7:0] y_or;
  (* src = "parameter_combinedgate.sv:11" *)
  output [7:0] y_xnor;
  (* src = "parameter_combinedgate.sv:8" *)
  output [7:0] y_xor;
  assign y_and[1] = a[1] & (* src = "parameter_combinedgate.sv:22" *) b[1];
  assign y_and[2] = a[2] & (* src = "parameter_combinedgate.sv:22" *) b[2];
  assign y_and[3] = a[3] & (* src = "parameter_combinedgate.sv:22" *) b[3];
  assign y_and[0] = a[0] & (* src = "parameter_combinedgate.sv:22" *) b[0];
  assign y_and[4] = a[4] & (* src = "parameter_combinedgate.sv:22" *) b[4];
  assign y_and[5] = a[5] & (* src = "parameter_combinedgate.sv:22" *) b[5];
  assign y_and[6] = a[6] & (* src = "parameter_combinedgate.sv:22" *) b[6];
  assign y_and[7] = a[7] & (* src = "parameter_combinedgate.sv:22" *) b[7];
  assign y_nand[1] = ~ (* src = "parameter_combinedgate.sv:22" *) y_and[1];
  assign y_nand[2] = ~ (* src = "parameter_combinedgate.sv:22" *) y_and[2];
  assign y_nand[3] = ~ (* src = "parameter_combinedgate.sv:22" *) y_and[3];
  assign y_nand[4] = ~ (* src = "parameter_combinedgate.sv:22" *) y_and[4];
  assign y_nand[0] = ~ (* src = "parameter_combinedgate.sv:22" *) y_and[0];
  assign y_nand[5] = ~ (* src = "parameter_combinedgate.sv:22" *) y_and[5];
  assign y_nand[6] = ~ (* src = "parameter_combinedgate.sv:22" *) y_and[6];
  assign y_nand[7] = ~ (* src = "parameter_combinedgate.sv:22" *) y_and[7];
  assign y_nor[1] = ~ (* src = "parameter_combinedgate.sv:23" *) y_or[1];
  assign y_nor[2] = ~ (* src = "parameter_combinedgate.sv:23" *) y_or[2];
  assign y_nor[3] = ~ (* src = "parameter_combinedgate.sv:23" *) y_or[3];
  assign y_nor[4] = ~ (* src = "parameter_combinedgate.sv:23" *) y_or[4];
  assign y_nor[5] = ~ (* src = "parameter_combinedgate.sv:23" *) y_or[5];
  assign y_nor[0] = ~ (* src = "parameter_combinedgate.sv:23" *) y_or[0];
  assign y_nor[6] = ~ (* src = "parameter_combinedgate.sv:23" *) y_or[6];
  assign y_nor[7] = ~ (* src = "parameter_combinedgate.sv:23" *) y_or[7];
  assign y_xnor[1] = ~ (* src = "parameter_combinedgate.sv:24" *) y_xor[1];
  assign y_xnor[2] = ~ (* src = "parameter_combinedgate.sv:24" *) y_xor[2];
  assign y_xnor[3] = ~ (* src = "parameter_combinedgate.sv:24" *) y_xor[3];
  assign y_xnor[4] = ~ (* src = "parameter_combinedgate.sv:24" *) y_xor[4];
  assign y_xnor[5] = ~ (* src = "parameter_combinedgate.sv:24" *) y_xor[5];
  assign y_xnor[6] = ~ (* src = "parameter_combinedgate.sv:24" *) y_xor[6];
  assign y_xnor[7] = ~ (* src = "parameter_combinedgate.sv:24" *) y_xor[7];
  assign y_xnor[0] = ~ (* src = "parameter_combinedgate.sv:24" *) y_xor[0];
  assign y_not_a[0] = ~ (* src = "parameter_combinedgate.sv:25" *) a[0];
  assign y_not_a[1] = ~ (* src = "parameter_combinedgate.sv:25" *) a[1];
  assign y_not_a[2] = ~ (* src = "parameter_combinedgate.sv:25" *) a[2];
  assign y_not_a[3] = ~ (* src = "parameter_combinedgate.sv:25" *) a[3];
  assign y_not_a[4] = ~ (* src = "parameter_combinedgate.sv:25" *) a[4];
  assign y_not_a[5] = ~ (* src = "parameter_combinedgate.sv:25" *) a[5];
  assign y_not_a[6] = ~ (* src = "parameter_combinedgate.sv:25" *) a[6];
  assign y_not_a[7] = ~ (* src = "parameter_combinedgate.sv:25" *) a[7];
  assign y_not_b[0] = ~ (* src = "parameter_combinedgate.sv:26" *) b[0];
  assign y_not_b[1] = ~ (* src = "parameter_combinedgate.sv:26" *) b[1];
  assign y_not_b[2] = ~ (* src = "parameter_combinedgate.sv:26" *) b[2];
  assign y_not_b[3] = ~ (* src = "parameter_combinedgate.sv:26" *) b[3];
  assign y_not_b[4] = ~ (* src = "parameter_combinedgate.sv:26" *) b[4];
  assign y_not_b[5] = ~ (* src = "parameter_combinedgate.sv:26" *) b[5];
  assign y_not_b[6] = ~ (* src = "parameter_combinedgate.sv:26" *) b[6];
  assign y_not_b[7] = ~ (* src = "parameter_combinedgate.sv:26" *) b[7];
  assign y_or[1] = a[1] | (* src = "parameter_combinedgate.sv:23" *) b[1];
  assign y_or[2] = a[2] | (* src = "parameter_combinedgate.sv:23" *) b[2];
  assign y_or[3] = a[3] | (* src = "parameter_combinedgate.sv:23" *) b[3];
  assign y_or[4] = a[4] | (* src = "parameter_combinedgate.sv:23" *) b[4];
  assign y_or[0] = a[0] | (* src = "parameter_combinedgate.sv:23" *) b[0];
  assign y_or[5] = a[5] | (* src = "parameter_combinedgate.sv:23" *) b[5];
  assign y_or[6] = a[6] | (* src = "parameter_combinedgate.sv:23" *) b[6];
  assign y_or[7] = a[7] | (* src = "parameter_combinedgate.sv:23" *) b[7];
  assign y_xor[1] = a[1] ^ (* src = "parameter_combinedgate.sv:24" *) b[1];
  assign y_xor[2] = a[2] ^ (* src = "parameter_combinedgate.sv:24" *) b[2];
  assign y_xor[3] = a[3] ^ (* src = "parameter_combinedgate.sv:24" *) b[3];
  assign y_xor[4] = a[4] ^ (* src = "parameter_combinedgate.sv:24" *) b[4];
  assign y_xor[5] = a[5] ^ (* src = "parameter_combinedgate.sv:24" *) b[5];
  assign y_xor[6] = a[6] ^ (* src = "parameter_combinedgate.sv:24" *) b[6];
  assign y_xor[0] = a[0] ^ (* src = "parameter_combinedgate.sv:24" *) b[0];
  assign y_xor[7] = a[7] ^ (* src = "parameter_combinedgate.sv:24" *) b[7];
endmodule
