/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module counter(clk, reset, count);
  wire [7:0] _0_;
  input clk;
  output [7:0] count;
  reg [7:0] count;
  input reset;
  assign _0_ = count + 1'h1;
  always @(posedge clk or posedge reset)
    if (reset)
      count <= 8'h00;
    else
      count <= _0_;
endmodule
