/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module up_down_counter(clk, reset, up, count);
  wire [7:0] _0_;
  wire [7:0] _1_;
  wire [7:0] _2_;
  input clk;
  output [7:0] count;
  reg [7:0] count;
  input reset;
  input up;
  assign _1_ = count + 1'h1;
  always @(posedge clk or posedge reset)
    if (reset)
      count <= 8'h00;
    else
      count <= _0_;
  assign _0_ = up ? _1_ : _2_;
  assign _2_ = count - 1'h1;
endmodule
