/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module simple_ram_16bit(clk, write_enable, address, write_data, read_data);
  wire [7:0] _00_;
  wire [15:0] _01_;
  wire [15:0] _02_;
  wire [15:0] _03_;
  reg [7:0] _04_;
  reg [15:0] _05_;
  reg [15:0] _06_;
  input [7:0] address;
  input clk;
  output [15:0] read_data;
  reg [15:0] read_data;
  input [15:0] write_data;
  input write_enable;
  reg [15:0] memory [255:0];
  \$memrd  #(
    .ABITS(32'd8),
    .CLK_ENABLE(32'd0),
    .CLK_POLARITY(32'd0),
    .MEMID("\\memory"),
    .TRANSPARENT(32'd0),
    .WIDTH(32'd16)
  ) _07_ (
    .ADDR(address),
    .CLK(1'hx),
    .DATA(_03_),
    .EN(1'hx)
  );
  \$memwr  #(
    .ABITS(32'd8),
    .CLK_ENABLE(32'd0),
    .CLK_POLARITY(32'd0),
    .MEMID("\\memory"),
    .PRIORITY(32'd7),
    .WIDTH(32'd16)
  ) _08_ (
    .ADDR(_04_),
    .CLK(1'hx),
    .DATA(_05_),
    .EN(_06_)
  );
  always @(posedge clk)
      _04_ <= _00_;
  always @(posedge clk)
      _05_ <= _01_;
  always @(posedge clk)
      _06_ <= { _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15] };
  always @(posedge clk)
      read_data <= _03_;
  assign _01_ = write_enable ? write_data : 16'hxxxx;
  assign _00_ = write_enable ? address : 8'hxx;
  assign _02_[15] = write_enable ? 1'h1 : 1'h0;
  assign _02_[14:0] = { _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15], _02_[15] };
endmodule
