/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module mux_if(a, b, sel, y);
  input a;
  wire a;
  input b;
  wire b;
  input sel;
  wire sel;
  output y;
  wire y;
  assign y = sel ? b : a;
endmodule
