/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module comb_logic(a, b, c, y);
  wire _0_;
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  output y;
  wire y;
  assign _0_ = b & a;
  assign y = _0_ | c;
endmodule
