/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter(clk, reset, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [7:0] _08_;
  wire [7:0] _09_;
  input clk;
  wire clk;
  output [7:0] count;
  reg [7:0] count;
  input reset;
  wire reset;
  assign _08_[0] = ~count[0];
  assign _00_ = ~(count[1] & count[0]);
  assign _09_[2] = ~(_00_ ^ count[2]);
  assign _01_ = count[2] & ~(_00_);
  assign _09_[3] = _01_ ^ count[3];
  assign _02_ = ~(count[3] & count[2]);
  assign _03_ = _02_ | _00_;
  assign _09_[4] = ~(_03_ ^ count[4]);
  assign _04_ = count[4] & ~(_03_);
  assign _09_[5] = _04_ ^ count[5];
  assign _05_ = ~(count[5] & count[4]);
  assign _06_ = _05_ | _03_;
  assign _09_[6] = ~(_06_ ^ count[6]);
  assign _07_ = count[6] & ~(_06_);
  assign _09_[7] = _07_ ^ count[7];
  assign _09_[1] = count[1] ^ count[0];
  always @(posedge clk, posedge reset)
    if (reset) count[0] <= 1'h0;
    else count[0] <= _08_[0];
  always @(posedge clk, posedge reset)
    if (reset) count[1] <= 1'h0;
    else count[1] <= _09_[1];
  always @(posedge clk, posedge reset)
    if (reset) count[2] <= 1'h0;
    else count[2] <= _09_[2];
  always @(posedge clk, posedge reset)
    if (reset) count[3] <= 1'h0;
    else count[3] <= _09_[3];
  always @(posedge clk, posedge reset)
    if (reset) count[4] <= 1'h0;
    else count[4] <= _09_[4];
  always @(posedge clk, posedge reset)
    if (reset) count[5] <= 1'h0;
    else count[5] <= _09_[5];
  always @(posedge clk, posedge reset)
    if (reset) count[6] <= 1'h0;
    else count[6] <= _09_[6];
  always @(posedge clk, posedge reset)
    if (reset) count[7] <= 1'h0;
    else count[7] <= _09_[7];
  assign _08_[7:1] = count[7:1];
  assign _09_[0] = _08_[0];
endmodule
