/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "counter.sv:1" *)
module counter(clk, reset, count);
  (* src = "counter.sv:14" *)
  wire [7:0] _0_;
  (* src = "counter.sv:4" *)
  input clk;
  (* src = "counter.sv:6" *)
  output [7:0] count;
  reg [7:0] count;
  (* src = "counter.sv:5" *)
  input reset;
  assign _0_ = count + (* src = "counter.sv:18" *) 1'h1;
  always @(posedge clk or posedge reset)
    if (reset)
      count <= 8'h00;
    else
      count <= _0_;
endmodule
