/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module logic_gates(a, b, and_out, or_out, nand_out, nor_out);
  input a;
  wire a;
  output and_out;
  wire and_out;
  input b;
  wire b;
  output nand_out;
  wire nand_out;
  output nor_out;
  wire nor_out;
  output or_out;
  wire or_out;
  assign and_out = b & a;
  assign or_out = b | a;
  assign nand_out = ~(b & a);
  assign nor_out = ~(b | a);
endmodule
