/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module fsm(clk, reset, start, finish, busy, done, current_state);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  output busy;
  wire busy;
  input clk;
  wire clk;
  output [1:0] current_state;
  reg [1:0] current_state;
  output done;
  wire done;
  input finish;
  wire finish;
  wire [1:0] next_state;
  input reset;
  wire reset;
  input start;
  wire start;
  assign _01_ = current_state[0] | current_state[1];
  assign _02_ = _01_ | start;
  assign _03_ = current_state[1] & ~(current_state[0]);
  assign _04_ = _03_ & ~(finish);
  assign _00_ = _02_ & ~(_04_);
  assign busy = current_state[0] ^ current_state[1];
  assign done = current_state[0] & current_state[1];
  assign _05_ = ~(current_state[0] | current_state[1]);
  assign next_state[0] = _05_ | _03_;
  assign next_state[1] = busy & ~(_05_);
  always @(posedge clk, posedge reset)
    if (reset) current_state[0] <= 1'h0;
    else if (_00_) current_state[0] <= next_state[0];
  always @(posedge clk, posedge reset)
    if (reset) current_state[1] <= 1'h0;
    else if (_00_) current_state[1] <= next_state[1];
endmodule
