/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module parameterized_fifo(clk, reset, write_enable, read_enable, write_data, read_data, full, empty, count, overflow, underflow);
  wire [3:0] _000_;
  wire [7:0] _001_;
  wire [7:0] _002_;
  wire [7:0] _003_;
  wire [7:0] _004_;
  wire [7:0] _005_;
  wire [7:0] _006_;
  wire [7:0] _007_;
  wire [7:0] _008_;
  wire _009_;
  wire [7:0] _010_;
  wire [2:0] _011_;
  wire _012_;
  wire [2:0] _013_;
  wire [7:0] _014_;
  wire [2:0] _015_;
  wire [2:0] _016_;
  wire [3:0] _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire [7:0] _024_;
  wire _025_;
  wire [7:0] _026_;
  wire _027_;
  wire [7:0] _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire [2:0] _032_;
  wire [2:0] _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire [7:0] _041_;
  wire [7:0] _042_;
  wire _043_;
  wire [7:0] _044_;
  wire _045_;
  wire [7:0] _046_;
  wire _047_;
  wire [7:0] _048_;
  wire _049_;
  wire [3:0] _050_;
  input clk;
  output [3:0] count;
  reg [3:0] count_register;
  output empty;
  output full;
  reg [7:0] \memory[0] ;
  reg [7:0] \memory[1] ;
  reg [7:0] \memory[2] ;
  reg [7:0] \memory[3] ;
  reg [7:0] \memory[4] ;
  reg [7:0] \memory[5] ;
  reg [7:0] \memory[6] ;
  reg [7:0] \memory[7] ;
  output overflow;
  reg overflow;
  output [7:0] read_data;
  reg [7:0] read_data;
  input read_enable;
  reg [2:0] read_pointer;
  input reset;
  output underflow;
  reg underflow;
  input [7:0] write_data;
  input write_enable;
  reg [2:0] write_pointer;
  assign _015_ = write_pointer + 1'h1;
  assign _016_ = read_pointer + 1'h1;
  assign _017_ = count_register + 1'h1;
  assign full = count_register == 4'h8;
  assign empty = ! count_register;
  assign _009_ = write_enable && full;
  assign _012_ = read_enable && empty;
  assign _021_ = read_enable && _023_;
  assign _020_ = write_enable && _022_;
  assign _023_ = ! empty;
  assign _022_ = ! full;
  always @(posedge clk or posedge reset)
    if (reset)
      read_data <= 8'h00;
    else
      read_data <= _010_;
  always @(posedge clk or posedge reset)
    if (reset)
      overflow <= 1'h0;
    else
      overflow <= _009_;
  always @(posedge clk or posedge reset)
    if (reset)
      underflow <= 1'h0;
    else
      underflow <= _012_;
  always @(posedge clk or posedge reset)
    if (reset)
      write_pointer <= 3'h0;
    else
      write_pointer <= _013_;
  always @(posedge clk or posedge reset)
    if (reset)
      read_pointer <= 3'h0;
    else
      read_pointer <= _011_;
  always @(posedge clk or posedge reset)
    if (reset)
      count_register <= 4'h0;
    else
      count_register <= _000_;
  always @(posedge clk)
      \memory[0]  <= _001_;
  always @(posedge clk)
      \memory[1]  <= _002_;
  always @(posedge clk)
      \memory[2]  <= _003_;
  always @(posedge clk)
      \memory[3]  <= _004_;
  always @(posedge clk)
      \memory[4]  <= _005_;
  always @(posedge clk)
      \memory[5]  <= _006_;
  always @(posedge clk)
      \memory[6]  <= _007_;
  always @(posedge clk)
      \memory[7]  <= _008_;
  assign _024_ = _025_ ? write_data : \memory[2] ;
  assign _025_ = write_pointer == 3'h2;
  assign _003_ = _020_ ? _024_ : \memory[2] ;
  assign _026_ = _027_ ? write_data : \memory[1] ;
  assign _027_ = write_pointer == 3'h1;
  assign _002_ = _020_ ? _026_ : \memory[1] ;
  assign _028_ = _029_ ? write_data : \memory[0] ;
  assign _029_ = ! write_pointer;
  assign _001_ = _020_ ? _028_ : \memory[0] ;
  function [3:0] _085_;
    input [3:0] a;
    input [7:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _085_ = b[3:0];
      2'b1?:
        _085_ = b[7:4];
      default:
        _085_ = a;
    endcase
  endfunction
  assign _000_ = _085_(count_register, { _017_, _050_ }, { _031_, _030_ });
  assign _030_ = { _020_, _021_ } == 2'h1;
  assign _031_ = { _020_, _021_ } == 2'h2;
  assign _032_ = _019_ ? 3'h0 : _016_;
  assign _011_ = _021_ ? _032_ : read_pointer;
  assign _033_ = _018_ ? 3'h0 : _015_;
  assign _013_ = _020_ ? _033_ : write_pointer;
  assign _010_ = _021_ ? _014_ : read_data;
  function [7:0] _093_;
    input [7:0] a;
    input [63:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _093_ = b[7:0];
      8'b??????1?:
        _093_ = b[15:8];
      8'b?????1??:
        _093_ = b[23:16];
      8'b????1???:
        _093_ = b[31:24];
      8'b???1????:
        _093_ = b[39:32];
      8'b??1?????:
        _093_ = b[47:40];
      8'b?1??????:
        _093_ = b[55:48];
      8'b1???????:
        _093_ = b[63:56];
      default:
        _093_ = a;
    endcase
  endfunction
  assign _014_ = _093_(8'hxx, { \memory[0] , \memory[1] , \memory[2] , \memory[3] , \memory[4] , \memory[5] , \memory[6] , \memory[7]  }, { _040_, _039_, _038_, _037_, _036_, _035_, _034_, _019_ });
  assign _019_ = read_pointer == 3'h7;
  assign _034_ = read_pointer == 3'h6;
  assign _035_ = read_pointer == 3'h5;
  assign _036_ = read_pointer == 3'h4;
  assign _037_ = read_pointer == 3'h3;
  assign _038_ = read_pointer == 3'h2;
  assign _039_ = read_pointer == 3'h1;
  assign _040_ = ! read_pointer;
  assign _041_ = _018_ ? write_data : \memory[7] ;
  assign _018_ = write_pointer == 3'h7;
  assign _008_ = _020_ ? _041_ : \memory[7] ;
  assign _042_ = _043_ ? write_data : \memory[6] ;
  assign _043_ = write_pointer == 3'h6;
  assign _007_ = _020_ ? _042_ : \memory[6] ;
  assign _044_ = _045_ ? write_data : \memory[5] ;
  assign _045_ = write_pointer == 3'h5;
  assign _006_ = _020_ ? _044_ : \memory[5] ;
  assign _046_ = _047_ ? write_data : \memory[4] ;
  assign _047_ = write_pointer == 3'h4;
  assign _005_ = _020_ ? _046_ : \memory[4] ;
  assign _048_ = _049_ ? write_data : \memory[3] ;
  assign _049_ = write_pointer == 3'h3;
  assign _004_ = _020_ ? _048_ : \memory[3] ;
  assign _050_ = count_register - 1'h1;
  assign count = count_register;
endmodule
