/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module xnor_gate(a, b, y);
  wire _0_;
  input a;
  wire a;
  input b;
  wire b;
  output y;
  wire y;
  assign y = ~_0_;
  assign _0_ = a ^ b;
endmodule
