/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "dflipflop.sv:3" *)
module dff_1bit(clk, reset, d, q);
  (* src = "dflipflop.sv:4" *)
  input clk;
  (* src = "dflipflop.sv:6" *)
  input d;
  (* src = "dflipflop.sv:7" *)
  output q;
  (* src = "dflipflop.sv:5" *)
  input reset;
  (* src = "dflipflop.sv:11" *)
  \$_DFF_PP0_  q_reg /* _0_ */ (
    .C(clk),
    .D(d),
    .Q(q),
    .R(reset)
  );
endmodule
