/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module full_adder(a, b, cin, sum, cout);
  wire _0_;
  wire _1_;
  wire _2_;
  input a;
  input b;
  input cin;
  output cout;
  output sum;
  assign _0_ = b ^ a;
  assign sum = _0_ ^ cin;
  assign _1_ = ~((cin | a) & b);
  assign _2_ = ~(cin & a);
  assign cout = ~(_2_ & _1_);
endmodule
