#!/usr/bin/env python3
"""Generate a default SDC for a design that doesn't ship hand-written
constraints.

Place and route needs timing constraints -- without a create_clock the tool
sees every path as unconstrained, CTS has nothing to build a tree for, and the
timing reports come out empty. Rather than make the user write an SDC for
every generated design, this derives a reasonable one from the RTL's port
list: a clock on whatever port looks like a clock, I/O delays at 20% of the
period, a driving cell on the inputs and a load on the outputs.

A hand-written constraints/<design>.sdc always wins; the Makefile only calls
this when that file is absent.

Usage: gen_sdc.py <rtl.sv> <design_name> <period_ns> <out.sdc>
"""
import re
import sys

# Port names treated as a clock, most-specific first. Matched case-insensitively
# against the module's input ports.
CLOCK_NAMES = ("clk", "clock", "clk_i", "i_clk", "clk_in", "sysclk", "ck")

# Ports excluded from set_input_delay along with the clock: an async reset is
# not a timed path in this flow, and constraining it just produces noise.
RESET_NAMES = ("rst", "reset", "rst_n", "resetn", "reset_n", "rst_i", "i_rst",
               "arst", "areset", "nrst")

DRIVING_CELL = "sky130_fd_sc_hd__buf_1"
DRIVING_PIN = "X"
OUTPUT_LOAD_PF = 0.02


def module_ports(text, design):
    """Return the input port names declared in `design`'s module header.

    Handles the ANSI style these designs use (`module foo (input logic clk,
    ...)`), which is all the generator emits. Comments are stripped first so a
    commented-out port doesn't get constrained.
    """
    text = re.sub(r"//[^\n]*", "", text)
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)

    match = re.search(
        r"\bmodule\s+" + re.escape(design) + r"\b[^(]*\((.*?)\)\s*;",
        text,
        flags=re.S,
    )
    if not match:
        return []

    inputs = []
    for decl in match.group(1).split(","):
        decl = decl.strip()
        if not decl.startswith("input"):
            continue
        # Drop the direction, any type/signedness keywords and a packed range,
        # leaving the identifier -- e.g. "input logic [2:0] addr" -> "addr".
        decl = re.sub(r"\[[^\]]*\]", " ", decl)
        tokens = [t for t in re.split(r"\s+", decl) if t]
        tokens = [t for t in tokens
                  if t not in ("input", "wire", "reg", "logic", "bit",
                               "signed", "unsigned")]
        if tokens:
            inputs.append(tokens[-1])
    return inputs


def find_clock(inputs):
    lowered = {name.lower(): name for name in inputs}
    for candidate in CLOCK_NAMES:
        if candidate in lowered:
            return lowered[candidate]
    return None


def main():
    if len(sys.argv) != 5:
        sys.exit("usage: gen_sdc.py <rtl.sv> <design_name> <period_ns> <out.sdc>")

    rtl_path, design, period_str, out_path = sys.argv[1:]
    period = float(period_str)

    with open(rtl_path) as handle:
        inputs = module_ports(handle.read(), design)

    clock = find_clock(inputs)
    excluded = {clock} if clock else set()
    excluded.update(name for name in inputs if name.lower() in RESET_NAMES)
    data_inputs = [name for name in inputs if name not in excluded]

    lines = [
        f"# Auto-generated by scripts/gen_sdc.py for '{design}'.",
        "# Override by hand-writing constraints/%s.sdc." % design,
        "",
        "set_units -time ns -capacitance pF",
        "",
    ]

    if clock:
        io_delay = round(period * 0.2, 3)
        lines += [
            f"create_clock -name core_clk -period {period} [get_ports {clock}]",
            "set_clock_uncertainty 0.25 [get_clocks core_clk]",
            "set_clock_transition 0.15 [get_clocks core_clk]",
            "",
        ]
        if data_inputs:
            ports = " ".join(data_inputs)
            lines.append(
                f"set_input_delay -clock core_clk {io_delay} [get_ports {{{ports}}}]"
            )
        lines += [
            f"set_output_delay -clock core_clk {io_delay} [all_outputs]",
            "",
        ]
    else:
        # Purely combinational: no clock to create, but the paths still need a
        # bound or the resizer and the timing reports have nothing to work with.
        lines += [
            "# No clock port found -- constraining the design as combinational.",
            f"set_max_delay {period} -from [all_inputs] -to [all_outputs]",
            "",
        ]

    if data_inputs:
        ports = " ".join(data_inputs)
        lines.append(
            f"set_driving_cell -lib_cell {DRIVING_CELL} -pin {DRIVING_PIN} "
            f"[get_ports {{{ports}}}]"
        )
    lines += [
        f"set_load {OUTPUT_LOAD_PF} [all_outputs]",
        "",
    ]

    with open(out_path, "w") as handle:
        handle.write("\n".join(lines))

    where = f"clock '{clock}'" if clock else "combinational (no clock port)"
    print(f"Wrote {out_path}: {where}, period {period} ns")


if __name__ == "__main__":
    main()
