/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module mux4(d, sel, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  input [3:0] d;
  input [1:0] sel;
  output y;
  assign _05_ = ~(sel[1] | sel[0]);
  assign _06_ = sel[1] & sel[0];
  assign _00_ = sel[1] & ~(sel[0]);
  assign _01_ = ~((_00_ & d[2]) | (_06_ & d[3]));
  assign _02_ = sel[1] | ~(sel[0]);
  assign _03_ = d[1] & ~(_02_);
  assign _04_ = _03_ | ~(_01_);
  assign y = _05_ ? d[0] : _04_;
endmodule
