/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module simple_ram(clk, write_enable, address, write_data, read_data);
  wire [15:0] _00_;
  wire [15:0] _01_;
  wire [15:0] _02_;
  input [15:0] address;
  wire [15:0] address;
  input clk;
  wire clk;
  output [15:0] read_data;
  reg [15:0] read_data;
  input [15:0] write_data;
  wire [15:0] write_data;
  input write_enable;
  wire write_enable;
  reg [15:0] memory [65535:0];
  always @(posedge clk) begin
    if (write_enable)
      memory[_00_] <= _01_;
  end
  assign _02_ = memory[address];
  assign _01_[0] = write_data[0] & write_enable;
  assign _01_[1] = write_enable & write_data[1];
  assign _01_[2] = write_enable & write_data[2];
  assign _01_[3] = write_enable & write_data[3];
  assign _01_[4] = write_enable & write_data[4];
  assign _01_[5] = write_enable & write_data[5];
  assign _01_[6] = write_enable & write_data[6];
  assign _01_[7] = write_enable & write_data[7];
  assign _01_[8] = write_enable & write_data[8];
  assign _01_[9] = write_enable & write_data[9];
  assign _01_[10] = write_enable & write_data[10];
  assign _01_[11] = write_enable & write_data[11];
  assign _01_[12] = write_enable & write_data[12];
  assign _01_[13] = write_enable & write_data[13];
  assign _01_[14] = write_enable & write_data[14];
  assign _01_[15] = write_enable & write_data[15];
  assign _00_[0] = write_enable & address[0];
  assign _00_[1] = write_enable & address[1];
  assign _00_[2] = write_enable & address[2];
  assign _00_[3] = write_enable & address[3];
  assign _00_[4] = write_enable & address[4];
  assign _00_[5] = write_enable & address[5];
  assign _00_[6] = write_enable & address[6];
  assign _00_[7] = write_enable & address[7];
  assign _00_[8] = write_enable & address[8];
  assign _00_[9] = write_enable & address[9];
  assign _00_[10] = write_enable & address[10];
  assign _00_[11] = write_enable & address[11];
  assign _00_[12] = write_enable & address[12];
  assign _00_[13] = write_enable & address[13];
  assign _00_[14] = write_enable & address[14];
  assign _00_[15] = write_enable & address[15];
  always @(posedge clk)
    read_data[0] <= _02_[0];
  always @(posedge clk)
    read_data[1] <= _02_[1];
  always @(posedge clk)
    read_data[2] <= _02_[2];
  always @(posedge clk)
    read_data[3] <= _02_[3];
  always @(posedge clk)
    read_data[4] <= _02_[4];
  always @(posedge clk)
    read_data[5] <= _02_[5];
  always @(posedge clk)
    read_data[6] <= _02_[6];
  always @(posedge clk)
    read_data[7] <= _02_[7];
  always @(posedge clk)
    read_data[8] <= _02_[8];
  always @(posedge clk)
    read_data[9] <= _02_[9];
  always @(posedge clk)
    read_data[10] <= _02_[10];
  always @(posedge clk)
    read_data[11] <= _02_[11];
  always @(posedge clk)
    read_data[12] <= _02_[12];
  always @(posedge clk)
    read_data[13] <= _02_[13];
  always @(posedge clk)
    read_data[14] <= _02_[14];
  always @(posedge clk)
    read_data[15] <= _02_[15];
endmodule
